// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkorqa_6d-eP4nqQEcFs6WPHjyz6D-8ts',
    appId: '1:186915296595:web:9f702d96ba09aaeee9bda6',
    messagingSenderId: '186915296595',
    projectId: 'ulam-5bd3f',
    authDomain: 'ulam-5bd3f.firebaseapp.com',
    storageBucket: 'ulam-5bd3f.appspot.com',
    measurementId: 'G-E73X1HQELQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeadSGWRHdxEwY05UAhgH3rCRMmHz9H3U',
    appId: '1:186915296595:android:ecfd0653ff7f1228e9bda6',
    messagingSenderId: '186915296595',
    projectId: 'ulam-5bd3f',
    storageBucket: 'ulam-5bd3f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSGS0yW1fsL6BdXSSvGUaKFsDSrNufoP8',
    appId: '1:186915296595:ios:d24de78a5174c9b0e9bda6',
    messagingSenderId: '186915296595',
    projectId: 'ulam-5bd3f',
    storageBucket: 'ulam-5bd3f.appspot.com',
    iosClientId: '186915296595-2nt74t7jccocqo0fb0d21uvvc1a92s0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.ulam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSGS0yW1fsL6BdXSSvGUaKFsDSrNufoP8',
    appId: '1:186915296595:ios:d24de78a5174c9b0e9bda6',
    messagingSenderId: '186915296595',
    projectId: 'ulam-5bd3f',
    storageBucket: 'ulam-5bd3f.appspot.com',
    iosClientId: '186915296595-2nt74t7jccocqo0fb0d21uvvc1a92s0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.ulam',
  );
}
